rootProject.name = 'FoodFusion'
include 'product-service'
include 'order-service'
include 'inventory-service'
include 'discovery-server'
include 'api-gateway'
include 'schemas'
include 'kafka-consumer'
include 'auth-service'
include 'workflow-service'
include 'notification-service'
include 'analytics-service'
include 'ai-assistant-service'
include 'config-server'
