{
  "name": "OrderEvent",
  "namespace": "com.foodfusion.avro.generated",
  "type": "record",
  "fields": [
    {
      "name": "id",
      "type": "long"
    },
    {
      "name": "orderNumber",
      "type": "string"
    },
    {
      "name": "userId",
      "type": "string",
      "default": "anonymous"
    },
    {
      "name": "orderLineItemsList",
      "type": {
        "type": "array",
        "items": {
          "name": "OrderLineItemsEvent",
          "type": "OrderLineItemsEvent"
        }
      }
    }
  ]
}
